frontend/components/shared/Heading/index.jsx, frontend/stories/Heading.stories.js
**Changes:** 
- Changed the output element tag depending on component type (to improve SEO).
- Added HEADING_OPTIONS object which contains all heading options to be more precise and avoid typos in props.
- Enhanced Heading storybook by introducing 2 components:
- **Code example** to be clear how to use the heading component.
- **Variations** a way to try every case of using the heading component using select menus and text inputs.
- Changed the default font weight to be black to mimic design
- Changed Main type font size to be responsive.
**State:** 
Ready to be reviewed.
=> Heading component Enhancment

frontend/components/Goals/index.jsx, frontend/components/Team/index.jsx, frontend/components/person-card/index.js, frontend/stories/Team.stories.js
create Team section using person card component
edit some styles in person card component
=> Team section

frontend/components/JoinUsComponent/index.jsx, frontend/components/shared/Button/index.jsx, frontend/stories/JoinUs.stories.js
I had to delete the branch because of a mistake I did, then I created a new branch with the latest updates and comments.
=> creating join us component

frontend/components/shared/SectionHeader/index.jsx, frontend/stories/SectionHeader.stories.js
_changes_
1/ Edit component to take **gradient_text prop** that has the gradient color
2/ Edit **heading type prop**
3/ add the **container inside** the component __ no need to add the container from the parent component
4/ add **margin-top and bottom** to the section
=> Fix header section issues

frontend/components/TopBar/index.jsx, frontend/styles/index.css, frontend/styles/topbar.css
change topbar btn **padding and font-size** at small screens using a custom class
=> fix TopBar responsive 

frontend/components/shared/Heading/index.jsx
- used tailwinds breakpoints to adjust heading font size on smaller screens
=> Fix Heading Responsive Font size

frontend/components/BackToHomeWithTitleAndImage/index.jsx, frontend/components/footer/index.jsx, frontend/stories/404component.stories.js, frontend/stories/404page.stories.js, frontend/stories/BackToHomeWithTitleAndImage.stories.js
- Added BackToHomeWithTitleAndImage component which will be suitable for any page like error 404 or coming soon or error 500
- Added an storybook for the component with 404 page data
=> Added Component for 404 page

backend/api/error-card/config/routes.json, backend/api/error-card/controllers/error-card.js, backend/api/error-card/models/error-card.js, backend/api/error-card/models/error-card.settings.json, backend/api/error-card/services/error-card.js
- Used the `Cards` component` and `Link` component
=> added ct error component

backend/api/batch-about/config/routes.json, backend/api/batch-about/controllers/batch-about.js, backend/api/batch-about/models/batch-about.js, backend/api/batch-about/models/batch-about.settings.json, backend/api/batch-about/services/batch-about.js, backend/api/batch-header/config/routes.json, backend/api/batch-header/controllers/batch-header.js, backend/api/batch-header/models/batch-header.js, backend/api/batch-header/models/batch-header.settings.json, backend/api/batch-header/services/batch-header.js, backend/api/batch-mentors/config/routes.json, backend/api/batch-mentors/controllers/batch-mentors.js, backend/api/batch-mentors/models/batch-mentors.js, backend/api/batch-mentors/models/batch-mentors.settings.json, backend/api/batch-mentors/services/batch-mentors.js, backend/api/batch-team/config/routes.json, backend/api/batch-team/controllers/batch-team.js, backend/api/batch-team/models/batch-team.js, backend/api/batch-team/models/batch-team.settings.json, backend/api/batch-team/services/batch-team.js, backend/api/join-us-card/config/routes.json, backend/api/join-us-card/controllers/join-us-card.js, backend/api/join-us-card/models/join-us-card.js, backend/api/join-us-card/models/join-us-card.settings.json, backend/api/join-us-card/services/join-us-card.js
create the batch page content type
=> Batch Page CT

backend/api/error-page/config/routes.json, backend/api/error-page/controllers/error-page.js, backend/api/error-page/models/error-page.js, backend/api/error-page/models/error-page.settings.json, backend/api/error-page/services/error-page.js
- Added content type for the error page.
=> added contet type for error page

backend/api/batch/models/batch.settings.json
- Added UID field for the `batch` component.
=> added UID fro batch content type

backend/extensions/upload/config/settings.json
-added configuration file for minio provider
=> added configuration for minio provider

frontend/clients/mentorship.js, frontend/components/Goals/index.jsx, frontend/components/Patches/index.jsx, frontend/components/how-it-work/index.jsx, frontend/components/patch-card/index.js, frontend/components/person-card/index.js, frontend/components/shared/SectionHeader/index.jsx, frontend/pages/index.jsx
fetch `Home` Page data by `getStaticProps` function
and edit some component's data destructure to match the incoming data
=> Next HomePage

backend/api/contribute/models/contribute.settings.json, backend/api/home-header/models/home-header.settings.json, frontend/components/shared/SectionHeader/index.jsx
**Changed:**
- header image content type name and used the same name in header section
note: in the near future header will be a content type component
=> Fixing header image position

frontend/components/Goals/index.jsx, frontend/components/Patches/index.jsx, frontend/components/how-it-work/index.jsx
=> use heading componet props

frontend/components/footer/index.jsx
1 -  make Links open in new tab 
2 - add a unique key to the li element 
3 - remove the unused underline destructure
=> Footer links edit

frontend/components/TopBar/index.jsx, frontend/package.json, frontend/yarn.lock
install framer-motion for animation
implement simple animation on topbar section
=> Install Framer

frontend/components/TopBar/index.jsx, frontend/components/how-it-work/index.jsx, frontend/components/person-card/index.js, frontend/helper/useMedia.jsx
fix Steps Small Screens animation 
fix TopBar section animation
=> Animation cards 

backend/api/apply-page-form/models/apply-page-form.settings.json, frontend/components/ApplyPage/index.jsx, frontend/components/Goals/index.jsx, frontend/components/ParagraphWithImageBeside/index.jsx, frontend/components/ParallaxedHeader/index.jsx, frontend/components/Patches/index.jsx, frontend/components/TeamSection/index.jsx, frontend/components/TopBar/index.jsx, frontend/components/apply/index.jsx, frontend/components/footer/index.jsx, frontend/components/how-it-work/index.jsx, frontend/pages/about.jsx, frontend/pages/apply.jsx, frontend/pages/batches/[slug].js, frontend/pages/index.jsx
**Changes:**
- Handled data error in whole application.
- Added some missing content type.
The approach I took in this PR isn't the best that can be done but it does the job.
Now at build time even if backend isn't deployed at all nextjs won't fail at building and it will build (mostly) blank pages, 
Once strapi is deployed and data is available , a simple refresh will re validate the data and get the data from strapi
=> Handled data error in application

frontend/components/TeamSection/index.jsx, frontend/yarn.lock
Create a Desktop animation to the team section card
=> Animation Team Section

frontend/components/ParagraphWithImageBeside/index.jsx, frontend/yarn.lock
add animation to the description section in about page
=> Animation About Page Description

backend/api/pages-seo/models/pages-seo.settings.json, backend/api/setting/models/setting.settings.json, backend/components/general/page-seo.json
-  and change the meta description field to be a rich text
=> Improvements for Page-seo CT

frontend/components/ProjectCard/index.jsx, frontend/components/RealProjects/index.jsx, frontend/stories/404page.stories.js, frontend/stories/BackToHomeWithTitleAndImage.stories.js, frontend/stories/ProjectCard.stories.js, frontend/stories/RealProjects.stories.js, frontend/tailwind.config.js
Create the project card Component
Create Real Projects Section
with the animation on each one of them and storybook to review
can review it by storybook
I hade to comment some code at 404 storybook and `BackToHomeWithTitleAndImage` file because it caused an error
=> Project card

frontend/pages/projects/[slug].js
- Add General Settings for Project Page and Fetching data Setup
=> Introduce Project page

frontend/components/ProjectCard/index.jsx, frontend/components/RealProjects/index.jsx, frontend/pages/index.jsx, frontend/public/sitemap.xml
fetch real projects section and projects data to add the real projects section to homepage
=> add Real Projects section to HomePage

frontend/pages/index.jsx
- handle error in case network failure
=> check if error exists

backend/api/pages/config/routes.json, backend/api/pages/controllers/pages.js, backend/api/pages/models/pages.js, backend/api/pages/models/pages.settings.json, backend/api/pages/services/pages.js
- added content type for pages
=> added pages content type

frontend/components/BatchProjects/index.jsx, frontend/components/CardItemComponent/index.jsx, frontend/pages/batches/[slug].js, frontend/stories/BatchProjects.stories.js, frontend/stories/CardItem.stories.js, frontend/styles/cardStyle.css
Crate The Batch's Projects section using the CardItem Component
Edit Some Styles at CardItem Component
Create Storybook and add animation
Just need to add it to batch page
In this PR I removed the old real projects section from the batch page and add the batch projects worked on instead
=> Batch's projects Section

frontend/components/CardItemComponent/index.jsx
- changed button size by using  the props named `btnSize`
=> chnanged button size

backend/api/sponser-us/config/routes.json, backend/api/sponser-us/controllers/sponser-us.js, backend/api/sponser-us/models/sponser-us.js, backend/api/sponser-us/models/sponser-us.settings.json, backend/api/sponser-us/services/sponser-us.js, backend/api/sponsers/config/routes.json, backend/api/sponsers/controllers/sponsers.js, backend/api/sponsers/models/sponsers.js, backend/api/sponsers/models/sponsers.settings.json, backend/api/sponsers/services/sponsers.js
- added content type for sponsors
=> added content type for sponsers

frontend/pages/batches/[slug].js
create a small condition
if The batch has one project `BatchProjects` section will hide and the two buttons at the `header` section will be shown
=> Batchpage projects Conditions 

backend/api/sponsers/models/sponsers.settings.json
- add `link` field to sponsors content type
=> added link field to sponsors content type

frontend/pages/batches/[slug].js
- keep the cohorts page structure consistent in case of single and multiple projects
=> Make Cohorts page consistent

frontend/components/apply/index.jsx
**The Problem** : Auto Scroll happens due to the Iframe,  when the iframe of typeForm is loaded it gets focused automatically
**Introduced Solution**: is to defer the loading of the iframe when it's get inView like lazy loading of an images
Fixes #260
=> Fix auto Scroll in Apply page

frontend/components/SponsorSection/index.jsx, frontend/tailwind.config.js
- removed unnecessary padding
- added width to the `img` tag wrapper
=> removed unncessary padding && set img wrapper width

frontend/components/patch-card/index.js
remove the margin from hover effect and make it a default margin
=> Fix/ Hover margin

frontend/components/SponsorSection/index.jsx, frontend/pages/index.jsx
Changed the button element to be down of the icons
move the whole section to be at the bottom of the page
=> Edit Sponsor Section

frontend/components/shared/Button/index.jsx, frontend/pages/projects/[slug].js, frontend/stories/Button/Button.stories.js, frontend/stories/PatchPage.stories.js, frontend/stories/SectionHeader.stories.js
- fixed typo in `Button` component props ~~`extranalLink`~~ to `externalLink`( missing e letter after `x`)
=> fixed typo in Button props externalLink

frontend/components/ListOfRoundedImages/index.jsx
- decrease the  interval between animating the images in cohort page ( Head section )
=>  decrease the value staggerChildren

backend/api/setting/models/setting.settings.json, frontend/components/ApplyPage/index.jsx, frontend/components/BatchProjects/index.jsx, frontend/components/Goals/index.jsx, frontend/components/JoinUsComponent/index.jsx, frontend/components/ListOfRoundedImages/index.jsx, frontend/components/Overview/index.jsx, frontend/components/ParagraphWithImageBeside/index.jsx, frontend/components/ParallaxedHeader/index.jsx, frontend/components/Patches/index.jsx, frontend/components/ProjectCard/index.jsx, frontend/components/RealProjects/index.jsx, frontend/components/Team/index.jsx, frontend/components/TeamSection/index.jsx, frontend/components/TopBar/index.jsx, frontend/components/apply/index.jsx, frontend/components/footer/index.jsx, frontend/components/how-it-work/index.jsx, frontend/components/person-card/index.js, frontend/components/resources/index.jsx, frontend/components/shared/SectionHeader/index.jsx, frontend/helper/useMobileAnimation.jsx, frontend/pages/about.jsx, frontend/pages/apply.jsx, frontend/pages/cohorts/[slug].js, frontend/pages/contact.jsx, frontend/pages/index.jsx, frontend/pages/projects/[slug].js, frontend/pages/sponsors.jsx
In this PR I created a new field at settings CT called `animated_at_mobile`
it's a boolean value
if it's true ==> the animation will work at mobile
if it's false ==> the animation won't work at mobile
I implemented it at person card component at steps at the home page
You can test it by changing the value of the content type and look to the component.
any comment will be consider
=> Toggle Animation At Mobile

frontend/components/TopBar/index.jsx, frontend/components/resources/index.jsx
resources link was in div instead of a tag ==> convert it to a tag to work when click
=> Fix Resources Link

frontend/pages/about.jsx
- removed the component used to display initiative founders
=> remove the founders section from apply page

frontend/components/BatchProjects/index.jsx, frontend/components/CardItemComponent/index.jsx
use flex-box to handle the height of the cohort projects to be the same for all cards
=> Fix Cohort projects height

frontend/components/ApplyPage/index.jsx, frontend/components/shared/SectionHeader/index.jsx
The Lazy Image Component prevented the change of the src attribute of the image dynamically.
=> Fix/Apply Page

frontend/pages/contact.jsx, frontend/pages/sponsors.jsx, frontend/styles/markdown.css
* changed width of element container
* align-text-left
=> Feature/sponsor contact markdown styling (#371)

frontend/components/apply/index.jsx
- increase mentee form height so that the content fit inside.
=> set mentee form hgeight to 50rem

frontend/components/apply/index.jsx
- increased mentee form height
=> set mentee form hgeight to 50rem (#376)

deploy/commons_fullstack/deployment.yaml
=> use default imagePullPolicy

.github/workflows/playground_fullstack_dev.yaml, .github/workflows/playground_fullstack_live.yaml, deploy/dev/fullstack/apply/ingress.yaml, deploy/live/fullstack/apply/ingress.yaml
use ingress networking.k8s.io/v1
=> use ingress networking.k8s.io/v1

deploy/live/fullstack/apply/ingress.yaml
=> add www subdomain
